Repository tethysplatform/tethys, pull requests merged in 2024-05, with the labels that each got.

#1044 Standalone App Non-Home Index Fixes
  tests/unit_tests/test_tethys_apps/test_decorators.py
  tests/unit_tests/test_tethys_apps/test_urls.py
  tests/unit_tests/test_tethys_apps/test_utilities.py
  tests/unit_tests/test_tethys_cli/test_app_settings_command.py
  tests/unit_tests/test_tethys_cli/test_list_commands.py
  tests/unit_tests/test_tethys_config/test_context_processors.py
  tests/unit_tests/test_tethys_layouts/test_views/test_map_layout.py
  tests/unit_tests/test_tethys_portal/test_asgi.py
  tests/unit_tests/test_tethys_portal/test_context_processors.py
  tests/unit_tests/test_tethys_portal/test_utilities.py
  tests/unit_tests/test_tethys_portal/test_views/test_accounts.py
  tests/unit_tests/test_tethys_portal/test_views/test_api.py
  tests/unit_tests/test_tethys_portal/test_views/test_user.py
  tethys_apps/decorators.py
  tethys_apps/urls.py
  tethys_apps/utilities.py
  tethys_config/context_processors.py
  tethys_portal/context_processors.py
  tethys_portal/templates/header.html
  tethys_portal/templates/tethys_portal/user/user_header_menu.html
  tethys_portal/utilities.py
  tethys_portal/views/accounts.py
  tethys_portal/views/api.py
  tethys_portal/views/user.py
Labels: bugfix

#1052 Add Workflow Matrix
  .github/workflows/tethys-release.yml
  .github/workflows/tethys.yml
  scripts/install_tethys.sh
Labels: POSE

#1055 Finish Fixing CI Deprecations
  .github/workflows/tethys-release.yml
  .github/workflows/tethys.yml
Labels: maintain dependencies

#1057 Fix Matrix Issue with Pinned Versions
  .github/workflows/tethys.yml
  Dockerfile
  scripts/install_tethys.sh
Labels: bugfix
