Repository tethysplatform/tethys, pull requests merged in 2024-09, with the labels that each got.

#1083 Tethys Portal Logo Update
  tests/unit_tests/test_tethys_config/test_init.py
  tethys_config/init.py
  tethys_config/migrations/0002_auto_20240820_2142.py
  tethys_portal/static/tethys_portal/images/tethys-on-blue-icon-only.svg
  tethys_portal/templates/footer.html
Labels: theme

#1072 Adds `tethys start` and `tethys quickstart` commands
  docs/images/getting_started/hello_world_app.png
  docs/images/getting_started/hello_world_login.png
  docs/index.rst
  docs/installation.rst
  tests/unit_tests/test_tethys_cli/test__init__.py
  tests/unit_tests/test_tethys_cli/test_install_commands.py
  tests/unit_tests/test_tethys_cli/test_scaffold_commands.py
  tests/unit_tests/test_tethys_cli/test_start_commands.py
  tethys_cli/__init__.py
  tethys_cli/gen_commands.py
  tethys_cli/install_commands.py
  tethys_cli/scaffold_commands.py
  tethys_cli/start_commands.py
Labels: minor feature

#1082 Async Handlers/Jobs Table
  .github/pull_request_template.md
  docs/installation/resources/example-portal-config.yml
  docs/supplementary/optional_features.rst
  docs/tethys_portal/configuration.rst
  docs/tethys_sdk/jobs.rst
  docs/tethys_sdk/routing.rst
  tests/unit_tests/test_tethys_apps/test_base/test_bokeh_handler.py
  tests/unit_tests/test_tethys_compute/test_models/test_TethysJob.py
  tests/unit_tests/test_tethys_gizmos/test_gizmo_options/test_map_view.py
  tests/unit_tests/test_tethys_gizmos/test_views/test_gizmos/test_jobs_table.py
  tethys_apps/base/bokeh_handler.py
  tethys_apps/base/controller.py
  tethys_cli/scaffold_templates/app_templates/react/reactapp/config/webpack.config.js_tmpl
  tethys_compute/migrations/0002_alter_tethysjob_options.py
  tethys_compute/models/tethys_job.py
  tethys_gizmos/gizmo_options/jobs_table.py
  tethys_gizmos/gizmo_options/map_view.py
  tethys_gizmos/static/tethys_gizmos/js/jobs_table.js
  tethys_gizmos/views/gizmos/jobs_table.py
  tethys_portal/settings.py
  tethys_portal/urls.py
Labels: major feature

#1088 Fix URL redirect for apps with no slash
  tests/unit_tests/test_tethys_apps/test_utilities.py
  tethys_apps/utilities.py
Labels: bugfix

#1091 Fixes for jobs table async compatibility
  tests/unit_tests/test_tethys_gizmos/test_views/test_gizmos/test_jobs_table.py
  tethys_gizmos/views/gizmos/jobs_table.py
Labels: async

#1090 Docker Production Docs
  docs/_static/css/tethys.css
  docs/installation/production.rst
  docs/installation/production/docker/docker_compose.rst
  docs/installation/production/docker/dockerfile.rst
  docs/tutorials/bokeh.rst
  docs/tutorials/thredds/plot_at_location.rst
  docs/tutorials/thredds/visualize_leaflet.rst
Labels: docs

#1095 HOTFIX: Patch to syncstores to enable support for PostGIS 3.4
  .github/workflows/tethys-release.yml
  .github/workflows/tethys.yml
  tests/unit_tests/test_tethys_apps/test_models/test_PersistentStoreDatabaseSetting.py
  tethys_apps/models.py
Labels: enhancement, maintain dependencies
